--- 
- name: Install Digital Rebar by RackN 2015
  hosts: all
  sudo: yes
  tasks:
    - include: tasks/ubuntu1404-base.yml
    - include: tasks/docker.yml

    - name: network mapping
      command: sudo ip a add 192.168.124.4/24 dev docker0
    - name: prep image [SLOW]
      command: docker pull ubuntu:14.04
    - name: Passwordless Sudo
      command: 'sudo sed -ie "s/%sudo\tALL=(ALL:ALL) ALL/%sudo ALL=(ALL) NOPASSWD:ALL/g" /etc/sudoers'
    - name: Make User
      user: name=vagrant groups=sudo,docker,kvm generate_ssh_key=yes
    - name: get code
      command: su -c "git clone https://github.com/digitalrebar/core.git" - vagrant
    - name: get code
      command: su -c "git clone https://github.com/rackn/kubernetes.git" - vagrant
    - name: noproxy
      command: su -c 'echo export no_proxy="127.0.0.1,[::1],localhost,192.168.124.0/24,172.16.0.0/12" >> /home/vagrant/.bashrc' - vagrant
    - name: make cache directory 
      command: su -c "mkdir -p /home/vagrant/.cache/digitalrebar/tftpboot/isos" - vagrant
    - name: download ISO [BACKGROUND] (see list https://github.com/digitalrebar/core/blob/develop/barclamps/provisioner.yml)
      command: su -c "nohup wget http://mirrors.kernel.org/ubuntu-releases/trusty/ubuntu-14.04.3-server-amd64.iso -nc -O /home/vagrant/.cache/digitalrebar/tftpboot/isos/ubuntu-14.04.2-server-amd64.iso &"
    - name: authorized keys
      command: cp /root/.ssh/authorized_keys -n --no-preserve=all /home/vagrant/.ssh/
    - name: Add groups
      command: sudo usermod -G docker,sudo,kvm vagrant
